# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'cocoa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.5'

  # Pods for cocoa

end
